### ISSUE TITLE
Next.JS - Server Error SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by ornakash** [n3ps/paste-from-excel#1]
I am trying to use this package but it tells me this:

 1 of 1 unhandled error
Server Error
SyntaxError: Unexpected token 'export'

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
<unknown>
file:///C:/ui-crypto-main/node_modules/paste-from-excel/src/index.js (61)
wrapSafe
internal/modules/cjs/loader.js (979:16)
Module._compile
internal/modules/cjs/loader.js (1027:27)
Object.Module._extensions..js
internal/modules/cjs/loader.js (1092:10)
Module.load
internal/modules/cjs/loader.js (928:32)
Function.Module._load
internal/modules/cjs/loader.js (769:14)
Module.require
internal/modules/cjs/loader.js (952:19)
require
internal/modules/cjs/helpers.js (88:18)
.next\server\pages\send.js (1:0) @ Object.paste-from-excel

> 1 | module.exports = require("paste-from-excel");;
Call Stack
__webpack_require__
.next\server\webpack-runtime.js (21:0)
Object../pages/components/SendMiddle.js
file:///C:/ui-crypto-main/.next/server/pages/send.js (189:74)
Hide collapsed frames`

Could you tell me what I  do wrong?

**Comment by n3ps** [comment]
@ornakash Can you tell me the version of NextJS you are using and reproducable steps?

**Comment by n3ps** [comment]
@ornakash This looks like a known issue with Next.js - https://github.com/vercel/next.js/issues/23725 

Pure ES Modules still don't work out of the box in Next.js. The workaround is to install `next-transpile-modules` and add this to your `next.config.js`

```js
const withTM = require('next-transpile-modules')(['paste-from-excel']);

module.exports = withTM();
```
